# Generated by Django 5.2 on 2025-05-02 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("reservation_date", models.DateField(auto_now=True)),
                ("reservation_time", models.TimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("phone_number", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerQuery",
            fields=[
                ("query_id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_name", models.CharField(max_length=255)),
                ("query", models.TextField()),
                ("answer", models.TextField(blank=True, null=True)),
                ("query_date", models.DateField(auto_now=True)),
                ("query_time", models.TimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("has_expired", models.BooleanField(default=False)),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saloon.customer",
                    ),
                ),
            ],
        ),
    ]
