# Generated by Django 5.2 on 2025-05-02 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saloon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerquery",
            name="was_resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customerquery",
            name="customer_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="saloon.customer",
            ),
        ),
    ]
