# Generated by Django 5.2 on 2025-05-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saloon", "0002_customerquery_was_resolved_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                ("answer", models.TextField()),
                ("source", models.CharField(blank=True, max_length=255)),
                ("tags", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "unique_together": {("query", "answer")},
            },
        ),
    ]
