# Generated by Django 5.2 on 2025-05-03 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("saloon", "0003_knowledgeentry"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="knowledgeentry",
            unique_together=set(),
        ),
    ]
